"""empty message

Revision ID: 3d342c4ee777
Revises: 545c53880f3f
Create Date: 2021-02-28 19:47:43.573642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d342c4ee777'
down_revision = '545c53880f3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Show_artist_image_link_fkey', 'Show', type_='foreignkey')
    op.drop_column('Show', 'artist_image_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('artist_image_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('Show_artist_image_link_fkey', 'Show', 'Artist', ['artist_image_link'], ['image_link'])
    # ### end Alembic commands ###
