"""empty message

Revision ID: 545c53880f3f
Revises: cfaa108ca84c
Create Date: 2021-02-28 19:15:52.847822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '545c53880f3f'
down_revision = 'cfaa108ca84c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'website')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
